services:
  app:
    platform: linux/x86_64
    image: commitglobal/one-roof:edge
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.$APP_NAME.rule=Host(`one-roof.staging.heroesof.tech`)
    env_file: .env
    environment:
      #   DB_HOST: host.docker.internal
      DB_HOST: 'staging.ce7zqk4ctcb0.eu-central-1.rds.amazonaws.com'
      DB_PORT: 3306
      DB_DATABASE: oneroof
      DB_USERNAME: admin
      DB_PASSWORD: 'JDNB9CAstxgL8j2iDorgLXude8xGw3a7'
    ports:
      - '80'
    volumes:
      - ./test-storage:/var/www/storage/app/public

volumes:
  database:
    driver: local
